[project]
name = "stargate"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.129.2",
    "httpx>=0.28.1",
    "pyjwt[crypto]>=2.11.0",
    "pyotp>=2.9.0",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.22",
    "python-telegram-bot>=22.6",
    "qrcode[terminal]>=8.2",
    "telegramify-markdown>=0.5.4",
    "uvicorn>=0.41.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
    "ruff>=0.9",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
