from __future__ import annotations

import subprocess
import time
import uuid
from pathlib import Path

from fastapi import APIRouter, File, Form, HTTPException, UploadFile
from fastapi.responses import JSONResponse

import asr as asr_mod
import tts as tts_mod
from chats import _chats, save_chats
from config import AUDIO_DIR
from pi_runner import run_pi

router = APIRouter()


@router.post("/api/talk")
async def talk(
    chat_id: str = Form(...),
    audio: UploadFile | None = File(None),
    text: str | None = Form(None),
    model: str | None = Form(None),
    audio_response: bool = Form(True),
    chunked_audio: bool = Form(False),
    tts_provider: str | None = Form(None),
    save_path: str | None = Form(None),
    auto_commit: bool = Form(False),
    create_agents_md: bool = Form(False),
    create_claude_md: bool = Form(False),
):
    if chat_id not in _chats:
        raise HTTPException(status_code=404, detail="Chat not found")
    chat = _chats[chat_id]

    t0 = time.time()

    if audio is not None:
        suffix = Path(audio.filename or "clip.webm").suffix or ".webm"
        tmp = AUDIO_DIR / f"in-{uuid.uuid4().hex}{suffix}"
        tmp.write_bytes(await audio.read())
        try:
            transcript = await asr_mod.transcribe(tmp)
        finally:
            tmp.unlink(missing_ok=True)
        t_asr = time.time()
    elif text:
        transcript = text.strip()
        t_asr = t0
    else:
        raise HTTPException(status_code=400, detail="Provide audio file or text field")

    if not transcript:
        return JSONResponse(
            {"transcript": "", "reply": "", "audio_url": None, "audio_urls": [], "note": "No speech detected."}
        )

    effective_save_path = (save_path or "docs/patchbay/").rstrip("/") + "/"

    if create_agents_md or create_claude_md:
        _ensure_context_files(chat.project_dir, effective_save_path, create_agents_md, create_claude_md)

    reply = await run_pi(transcript, chat, model=model, save_path=effective_save_path)
    t_llm = time.time()

    audio_paths: list[Path] = []
    if audio_response:
        audio_paths = await tts_mod.synthesize(reply, provider=tts_provider, chunked=chunked_audio)
    t_tts = time.time()

    chat.last_active = time.time()
    save_chats()

    if auto_commit:
        _auto_commit(chat.project_dir, effective_save_path)

    audio_urls = [f"/audio/{p.name}" for p in audio_paths]
    print(
        f"[turn] {chat.name} asr={t_asr - t0:.1f}s llm={t_llm - t_asr:.1f}s tts={t_tts - t_llm:.1f}s | "
        f"q={transcript!r} a={reply[:80]!r}",
        flush=True,
    )

    return JSONResponse(
        {
            "transcript": transcript,
            "reply": reply,
            "audio_url": audio_urls[0] if audio_urls else None,
            "audio_urls": audio_urls,
            "timing": {
                "asr": round(t_asr - t0, 2),
                "llm": round(t_llm - t_asr, 2),
                "tts": round(t_tts - t_llm, 2),
                "total": round(t_tts - t0, 2),
            },
        }
    )


def _ensure_context_files(project_dir: str, save_path: str, agents: bool, claude: bool) -> None:
    base = Path(project_dir) / save_path
    base.mkdir(parents=True, exist_ok=True)
    agents_content = (
        "This directory contains files generated by Patchbay Voice sessions.\n"
        "Patchbay Voice is a voice-controlled coding assistant iOS app that\n"
        "communicates with a Python backend server. Files here are created\n"
        "or modified by the AI assistant during voice coding sessions.\n"
    )
    if agents and not (base / "AGENTS.md").exists():
        (base / "AGENTS.md").write_text(agents_content)
    if claude and not (base / "CLAUDE.md").exists():
        (base / "CLAUDE.md").write_text("@AGENTS.md\n")


def _auto_commit(project_dir: str, save_path: str) -> None:
    save_abs = str(Path(project_dir) / save_path)
    try:
        subprocess.run(["git", "-C", project_dir, "add", save_abs], capture_output=True, check=False, timeout=10)
        subprocess.run(
            ["git", "-C", project_dir, "commit", "-m", "patchbay: voice session turn"],
            capture_output=True,
            check=False,
            timeout=10,
        )
    except Exception:
        pass
